version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app:cached
    stdin_open: true
    tty: true
    container_name: projeto-frontend
